GPUS: '0'
OUTPUT_DIR: 'output'
WORKERS: 8
DATASET:
  TYPE: MPII
  ROOT: 'data/mpii/'
  TEST_SET: valid
  TRAIN_SET: train
  FLIP: true
  ROT_FACTOR: 30
  SCALE_FACTOR: 0.25
MODEL:
  NAME: mpii_256_101
  PRETRAINED: ''
  IMAGE_SIZE:
  - 256
  - 256
  NUM_JOINTS: 16
  NUM_LAYERS: 101
  EXTRA:
    TARGET_TYPE: gaussian
    SIGMA: 3
    HEATMAP_SIZE:
    - 64
    - 64
TRAIN:
  BATCH_SIZE: 32
  EPOCH: 150
  LR: 0.001
  LR_STEP:
  - 90
  - 120
  LR_FACTOR: 0.1
TEST:
  BATCH_SIZE: 32
LOSS:
  USE_TARGET_WEIGHT: true
